services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agents
    ports:
      - 5433:5432
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  nlw-agents-server:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3333:3333
    environment:
      PORT: 3333
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: nlw-agents-pg
      POSTGRES_PORT: 5432
      POSTGRES_DB: agents
    depends_on:
      - nlw-agents-pg
    command: sh -c "npm install && npm run db:migrate && npm run db:seed && npm run dev"
